version: '3.0'

services:
  empty:
    build: ./docker_empty
  rabbitmq:
    hostname: dev-rabbitmq
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_PASS=pass
      - RABBITMQ_DEFAULT_USER=user
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbit_network
  producer_rabbitmq:
    build: ./docker_rabbimq-publisher
    networks:
      - rabbit_network
networks:
  rabbit_network:
    driver: bridge

